config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :collections do
    resources :resources do
      # cf. polymorphic routes
      resources :comments, only: [:create, :update, :destroy]
      member do
        put "like", to: "resources#upvote"
        put "dislike", to: "resources#downvote"
      end
    end
    member do
      put "like", to: "collections#like"
      put "follow", to: "collections#follow"
    end
    # cf. polymorphic routes
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :activities, only: :index

  resources :users, only: [:show] do
    member do
      put "follow", to: "users#follow"
    end
  end
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :resources, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user

  validates :title, presence: true;
  validates :title, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true;
  validates :description, length: { minimum: 5 }

  # acts_as_followable gem in order to allow users to follow a collection
  acts_as_followable
  # acts_as_votable gem (a collection can be voted by a user)
  acts_as_votable

  # Public_activity gem, for keeping track of of everything done by users on collections.
  include PublicActivity::Common
  # tracked owner: ->(controller, model) { controller && controller.current_user }

  # STATUS => Enumerated datatypes (stored as Integer in the database)
  enum status: { is_public: 0, is_open: 1, is_private: 2 }

  # Scopes
  scope :not_private, -> { where(status: [:is_open, :is_public]) }
  scope :created_by, ->(user) { where(user: user) }

  def self.statuses_with_symbols
    statuses.map { |k, v| [k.to_sym, v] }.to_h
  end

  def is_public_or_open?
    return !is_private?
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :like, :follow]
  skip_before_action :authenticate_user!, only: [ :show ]


  def index
    @collections = policy_scope(Collection)
  end

  def show
    @comment = Comment.new
  end

  def new
    @collection = Collection.new
    authorize @collection
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    authorize @collection
    @collection.save
    @collection.create_activity :create, owner: current_user
    redirect_to collection_path(@collection)
    # do a IF/ELSE statement on the save. in order to prevent errors...
  end

  def edit
  end

  def update
    authorize @collection
    @collection.update(collection_params)
    @collection.create_activity :update, owner: current_user
    redirect_to collection_path(@collection)
    # same here, muste do a IF/ELSE statement to handle errors
  end

  def destroy
    authorize @collection
    @collection.destroy
    redirect_to collections_path
  end

  # non-CRUD actions
  def like
    # refacto the IF ELSE statement in order to create activity only on the like (and not the dislike)
    @user = current_user
    if @user.liked? @collection
      @collection.disliked_by current_user
    else
      @user.likes @collection
    end
    @collection.create_activity :like, owner: current_user
    respond_to do |format|
      format.js  # <-- like.js.erb
    end
  end

  def follow
    if current_user.following? @collection
      current_user.stop_following @collection
    else
      current_user.follow @collection
      @collection.create_activity :follow, owner: current_user
    end
    respond_to do |format|
      format.js  # <-- follow.js.erb
    end
  end

  private

  def collection_params
    params.require(:collection).permit(:title, :description, :tagline, :status)
  end

  def set_collection
    @collection = Collection.find(params[:id])
    authorize @collection
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/edit.html.erb
<%= render "shared/collections/collection_form", collection: @collection %>

app/views/collections/follow.js.erb
var followActivated = "collection-follow-activated"

<% if current_user.following? @collection %>
  $('.collection-follow').addClass(followActivated);
<% else %>
  $('.collection-follow').removeClass(followActivated);
<% end %>

app/views/collections/index.html.erb
<div class="container">
  <% @collections.each do |collection| %>
    <%= render 'shared/collections/collection_item', collection: collection %>
  <% end %>
</div>

app/views/collections/like.js.erb
var favoriteActivated = "collection-favorite-activated"

<% if current_user.liked? @collection %>
  $('.collection-favorite').addClass(favoriteActivated);
  $('.collection-favorite > a > i').removeClass('fa-star-o').addClass('fa-star');
<% else %>
  $('.collection-favorite').removeClass(favoriteActivated);
  $('.collection-favorite > a > i').addClass('fa-star-o').removeClass('fa-star');
<% end %>

app/views/collections/new.html.erb
<%= render 'shared/collections/collection_form', collection: @collection %>

app/views/collections/show.html.erb
<div class="collection-wrapper">
  <div class="container">
    <div class="collection-header">
      <% if current_user %>
        <div class="collection-actions">
          <div class="collection-favorite <%= 'collection-favorite-activated' if current_user.voted_up_on?(@collection) %>" id="collection-<%= @collection.id %>">
            <p>Star</p>
            <%= link_to like_collection_path(@collection), method: :put, remote: true, id: "like-collection-#{@collection.id}" do %>
              <%= current_user.voted_up_on?(@collection) ? icon('star') : icon('star-o') %>
            <% end %>
          </div>
          <div class="collection-follow <%= 'collection-follow-activated' if current_user.following?(@collection) %>">
            <p>Follow</p>
            <%= link_to follow_collection_path(@collection), method: :put, remote: true, id: "follow-collection-#{@collection.id}" do %>
              <%= icon('eye') %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="collection-title-block">
        <div class="white-stripe">
          <h3><%= @collection.title %></h3>
        </div>
        <% if @collection.tagline %>
          <div class="collection-tagline">
            <div class="white-stripe">
              <p><%= @collection.tagline %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="collection-content">
  <div class="container">
    <div class="collection-status">Status: <%= t("collection.status.#{@collection.status}") %></div> <!-- .collection-status -->
    <div class="collection-description">
      <h4>Description:</h4>
      <p><%= @collection.description %></p>
    </div>

    <div class="collection-resources">
      <h4>Resources</h4>
      <% if policy(@collection).edit? %>
        <%= link_to "add a resource", new_collection_resource_path(@collection), class:"btn btn-primary", id:"resource-add-btn", remote: true %>
      <% end %>
      <% if policy(@collection).edit? %>
        <%= link_to "edit collection", edit_collection_path(@collection) %>
      <% end %>
      <% if policy(@collection).destroy? %>
        <%= link_to "delete this collection", collection_path(@collection), method: :delete, data: { confirm: "It will also delete all the resources inside this collection. Are you sure?" }  %>
      <% end %>
      <div class="resources-list">
        <% if @collection.resources.any? %>
        <!-- render the list of resources belonging to this collection -->
          <%= render 'shared/resources/resources_list', resources: @collection.resources %>
        <% else %>
          <p id="no-ressource-text">sorry, no resources attached to this collection yet</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- comments -->
<div class="collection-comments">
  <div class="container">
    <h4>Comments</h4>
    <div class="collection-comments-form">
    <!-- render the form for creating a comment -->
      <%= render 'shared/comments/collection_comment_form', comment: @comment, commentable: @collection %>
    </div>
    <div class="collection-comments-list">
    <!-- render the list of the comments -->
      <%= render 'shared/comments/comments_list', comments: @collection.comments %>
    </div>
  </div>
</div>