config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :collections do
    resources :resources do
      # cf. polymorphic routes
      resources :comments, only: [:create, :update, :destroy]
      member do
        put "like", to: "resources#upvote"
        put "dislike", to: "resources#downvote"
      end
    end
    member do
      put "like", to: "collections#like"
      put "follow", to: "collections#follow"
    end
    # cf. polymorphic routes
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :activities, only: :index

  resources :users, only: [:show] do
    member do
      put "follow", to: "users#follow"
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :user, presence: true;
  validates :content, presence: true;
  validates :content, length: { minimum: 5 };

  # public_activity gem
  include PublicActivity::Common

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable, only: [:create, :update, :destroy]
  before_action :set_comment, only: [:update, :destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.commentable = @commentable
    @comment.user = current_user
    if @comment.save
      @comment.create_activity :create, owner: current_user
      if @comment.commentable.class == Resource
        respond_to do |format|
          format.html { redirect_to collection_resource_path(@commentable.collection, @commentable) }
          format.js  # <-- will render `app/views/comment/create.js.erb`
        end
        # redirect_to collection_resource_path(@commentable.collection, @resource)
      elsif @comment.commentable.class == Collection
        # redirect_to collection_path(@commentable)
        respond_to do |format|
          format.html { redirect_to collection_path(@commentable) }
          format.js  # <-- will render `app/views/comment/create.js.erb`
        end
      end
    else
      if @comment.commentable.is_a? Resource
        respond_to do |format|
          format.html { render 'resources/show' }
          format.js  # <-- idem
        end
      else
        respond_to do |format|
          format.html { render 'collections/show' }
          format.js  # <-- idem
        end
      end
    end
  end

  def update
    # TODO (replace comment item for form to edit the comment)
  end

  def destroy
    @comment.destroy
    # if @commentable.is_a? Resource
    #   redirect_to collection_resource_path(@commentable.collection, @commentable)
    # else
    #   redirect_to collection_path(@commentable)
    # end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def set_commentable
    if params[:resource_id]
      @commentable = Resource.find(params[:resource_id])
    else
      @commentable = Collection.find(params[:collection_id])
    end
    authorize @commentable
  end

  # def set_collection
  #   @collection = Collection.find(params[:collection_id])
  # end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/shared/comments/_collection_comment_form.html.erb
<%= simple_form_for([commentable, comment], remote: true) do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a comment", class: "btn btn-primary" %>
<% end %>

app/views/shared/comments/_comment_form.html.erb
<%= simple_form_for [resource.collection, resource, comment] do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a comment", class: "btn btn-primary" %>
<% end %>

app/views/shared/comments/_comment_item.html.erb
<div class="comment-item" id="comment-<%= comment.id %>">
  <div class="comment-details">
    <p><%= comment.user.email %></p>
    <p> - </p>
    <p class='comment-time'><%= time_ago_in_words(comment.created_at) + " ago"%></p>
    <% if policy(comment).update? && policy(comment).destroy? %>

      <% if comment.commentable.is_a? Resource %>
        <p>|</p>
        <%= link_to 'edit', collection_resource_comment_path(comment.commentable.collection, comment.commentable, comment)  %>
        <%= link_to 'delete', collection_resource_comment_path(comment.commentable.collection, comment.commentable, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?", remote: true } %>
      <% else %>
        <p>|</p>
        <%= link_to 'edit', collection_comment_path(comment.commentable, comment)  %>
        <%= link_to 'delete', collection_comment_path(comment.commentable, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" }, remote: true  %>

      <% end %>
    <% end %>
  </div> <!-- .comment-details -->
  <div class="comment-content">
    <p class='comment-content-text'><%= comment.content %></p>
  </div> <!-- .comment-content -->
</div>

app/views/shared/comments/_comments_list.html.erb
<% comments.each do |comment| %>
  <%= render 'shared/comments/comment_item', comment: comment %>
<% end %>

app/views/shared/comments/_resource_comment_form.html.erb
<%= simple_form_for([commentable.collection, commentable, comment], remote: true) do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a comment", class: "btn btn-primary" %>
<% end %>