config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :collections do
    resources :resources do
      # cf. polymorphic routes
      resources :comments, only: [:create, :update, :destroy]
      member do
        put "like", to: "resources#upvote"
        put "dislike", to: "resources#downvote"
      end
    end
    member do
      put "like", to: "collections#like"
      put "follow", to: "collections#follow"
    end
    # cf. polymorphic routes
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :activities, only: :index

  resources :users, only: [:show] do
    member do
      put "follow", to: "users#follow"
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="footer-content">
      <div class="footer-credits">
        <p class="credits-text">© 2016 MNMLIST, Inc.</p>
      </div> <!-- .footer-credits -->
      <div class="footer-links">
        <%= link_to "About", "#" %>
        <%= link_to "Contact", "#" %>
        <%= link_to "Terms", "#" %>
        <%= link_to "Privacy", "#" %>
      </div> <!-- .footer-links -->
    </div> <!-- .footer-content -->
  </div> <!-- .container -->
</footer>

app/views/shared/_navbar.html.erb
<nav>
  <div class="container">
    <div class="navbar">
      <!-- Left part -->
      <div class="navbar-left hidden-sm hidden-xs">
      <!-- Logo -->
        <%= link_to root_path do %>
          <%= image_tag "mnmlist_logo.png" %>
        <% end %>
      </div>
      <!-- if the user is not signed in to the application -->
      <% unless user_signed_in? %>

        <div class="navbar-right">
          <%= link_to new_user_session_path do %>
            <button class="btn btn-mnml-empty btn-mnml-empty-reverse-color">Sign in</button>
          <% end %>
        </div>

      <% else %>
      <!-- now, if the user is signed in. -->

        <!-- Middle part (for search for instance)-->
        <div class="navbar-middle">

          <!-- Search form -->
          <form action="" class="navbar-search">
            <input type="text" class="navbar-search-input" id='search-input' placeholder="Discover your next favorite list">
            <div id="search-autocomplete-dropdown"></div> <!-- #search-autocomplete-dropdown -->
            <button type="submit" class="navbar-search-btn">
              <i class="fa fa-search"></i>
            </button>
          </form>

        </div>

        <!-- right part -->
        <div class="navbar-right hidden-sm hidden-xs">
          <!-- Call to action button -->
          <%= link_to new_collection_path do %>
            <button class="btn btn-mnml-empty btn-mnml-empty-reverse-color">New list</button>
          <% end %>
          <!-- Profile picture and dropdown -->
          <div class="navbar-profile-menu">
            <div class="dropdown">
              <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu dropdown-menu-left mnmlist-dropdown-menu">
                <li>
                  <%= link_to "#" do %>
                    <%= t(".profile", default: "PROFILE") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to root_path do %>
                    <%= t(".profile", default: "HOME") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <%= t(".sign_out", default: "LOG OUT") %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>




        <!-- Dropdown list appearing on mobile only -->
        <div class="navbar-right-mobile hidden-md hidden-lg">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right mnmlist-dropdown-menu mnmlist-dropdown-menu-mobile">
              <li>
                <%= link_to new_collection_path do %>
                  <%= t(".new_list", default: "NEW LIST") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <%= t(".profile", default: "PROFILE") %>
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <%= t(".profile", default: "HOME") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= t(".sign_out", default: "LOG OUT") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>


<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      console.log('hello');
      var algoliaAppId = "<%= ENV['ALGOLIA_APP_ID'] %>";
      var algoliaSearchOnlyId = "<%= ENV['ALGOLIA_SEARCH_ONLY_KEY'] %>";

      var client = algoliasearch( algoliaAppId, algoliaSearchOnlyId );

      var template = Hogan.compile('<span class="aa-dropdown-menu{{#datasets}} aa-{{\'with\' or \'without\'}}-{{name}}{{/datasets}}">' +
      '{{#datasets}}' + '<div class="aa-dataset-{{name}}">' + '{{{header}}}' +
      '<span class="aa-suggestions">' + '{{#suggestions}}' +
      '<div class="aa-suggestion">{{{suggestion}}}</div>' +
      '{{/suggestions}}' + '{{^suggestions}}' + '{{{empty}}}' +
      '{{/suggestions}}' + '</span>' + '{{{footer}}}' + '</div>' +
      '{{/datasets}}' + '{{empty}}' + '</span>');

      var index = client.initIndex('Collection');

      autocomplete('#search-input', { hint: false }, [
        {
          source: autocomplete.sources.hits(index, { hitsPerPage: 5 }),
          displayKey: 'title',
          templates: {
            footer: '<div class="algolia-branding">Powered by <img src="https://www.algolia.com/assets/algolia128x40.png" /></div>',
            suggestion: function(suggestion) {
              return template.render(suggestion);
            }
          }

          // templates: {
          //  dropdownMenu: '#search-autocomplete-dropdown',
          //  footer: '<div class="branding">Powered by <img src="https://www.algolia.com/assets/algolia128x40.png" /></div>'
          //}
        }
      ]).on('autocomplete:selected', function(event, suggestion, dataset) {
        console.log(suggestion, dataset);
      });
    });
  <% end %>
<% end %>