config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :collections do
    resources :resources do
      # cf. polymorphic routes
      resources :comments, only: [:create, :update, :destroy]
      member do
        put "like", to: "resources#upvote"
        put "dislike", to: "resources#downvote"
      end
    end
    member do
      put "like", to: "collections#like"
      put "follow", to: "collections#follow"
    end
    # cf. polymorphic routes
    resources :comments, only: [:create, :update, :destroy]
  end

  resources :activities, only: :index

  resources :users, only: [:show] do
    member do
      put "follow", to: "users#follow"
    end
  end
end

app/views/shared/resources/_resource_form.html.erb
<%= simple_form_for([collection, resource], remote: true) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :uri %>
  <%= f.submit "add a resource", class: "btn btn-primary" %>
<% end %>

app/views/shared/resources/_resource_form_non_ajax.html.erb
<%= simple_form_for([collection, resource]) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :uri %>
  <%= f.submit "add a resource", class: "btn btn-primary" %>
<% end %>

app/views/shared/resources/_resource_item.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="resource-item" id="resource-<%= resource.id %>">
      <div class="resource-item-content">
        <h5><%= link_to resource.title, collection_resource_path(resource.collection, resource) %></h5>
        <p><%= truncate resource.content, length: 150, seperator: ' ' %>
        <p><%= link_to resource.uri, resource.uri %></p>
      </div>
      <div class="resource-item-options">
        <%= render 'shared/resources/vote_btn', resource: resource %>
        <div class="resource-item-comments">
          <div class="resource-item-comments-nb">24</div>
          <p>comments</p>
        </div>
      </div>
      <% if policy(resource).edit? %>
        <div class="resource-item-admin-controls">
          <%= link_to "edit", edit_collection_resource_path(resource.collection, resource), id: "edit-resource-#{resource.id}" %>
          <%= link_to "delete", collection_resource_path(resource.collection, resource), id: "edit-resource-#{resource.id}", method: :delete, data: { confirm: "are you sure your want to delete this resource?" }  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/resources/_resources_list.html.erb
<% resources.each do |resource| %>
  <%= render "shared/resources/resource_item", resource: resource %>
<% end %>

app/views/shared/resources/_vote_btn.html.erb
<div class="vote-panel">
  <%= link_to like_collection_resource_path(resource.collection, resource), class:"upvote-btn", id: "upvote-btn-resource-#{resource.id}", method: :put, remote: true do %>
    <div class="up-arrow">
      <%= icon('angle-up') %>
    </div>
    <p id='resource-<%= resource.id %>-upvotes'><%= resource.get_upvotes.size %></p>
  <% end %>
  <%= link_to dislike_collection_resource_path(resource.collection, resource), class:"downvote-btn", method: :put, remote: true do %>
    <div class="down-arrow">
      <%= icon('angle-down') %>
    </div>
  <% end %>
</div>